### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by kewpac95** [teddykoker/survivorship-free-spy#3]
Hello, 
When I am trying to run your code I had error: list index out of range
 in 'dates_div = holdings.find_all("div", "component-date-list")[1]'

Are you sure, that it should be '[1]'?
Regards K.P.

**Comment by teddykoker** [comment]
Hi @kewpac95 - unfortunately due to the dynamic nature of the source website, I cannot keep the web-scraping code up to date. The last web scrape was performed 3 years ago, and structure/information of the page(s) has likely changed, which means the existing web scraping code likely does not work. Feel free to use the included scraped historical data, but you might need to do some work re-scrape the constituents, and the constituents may not all even be available on the current website. Please let me know if you have any other questions! -Teddy
